export const Routes = {
  admin: "/admin",
  dashboard: "/admin/dashboard",
  login: "/admin/login",
  register: "/admin/register",
  categories: "/admin/categories",
  foods: "/admin/foods",
  tables: "/admin/tables",
  staffs: "/admin/staffs",
  roles: "/admin/roles",
  orders: "/admin/orders",
  payments: "/admin/payments",
  settings: "/admin/settings",
  reports: "/admin/reports",
};
